### ISSUE TITLE
Align definition of `bins` with numpy.histogram

### ISSUE THREAD

**Issue by dougiesquire** [xgcm/xhistogram#18]
When bin edges are specified in `numpy.histogram`, the last bin is closed on both sides. From the `numpy` docs (https://numpy.org/doc/stable/reference/generated/numpy.histogram.html):
> All but the last (righthand-most) bin is half-open. In other words, if bins is:
> 
> [1, 2, 3, 4]
> then the first bin is [1, 2) (including 1, but excluding 2) and the second [2, 3). The last bin, however, is [3, 4], which includes 4.

This is not the case for `xhistogram`, e.g.:
```python
import numpy as np
import xarray as xr
from xhistogram.xarray import histogram as xhist

data = np.ones(10)
da =  xr.DataArray(data, coords=[range(10)], dims=['x']).rename('test')

bins = np.array([0, 0.5, 1])

print(f'xhistogram: {xhist(da, bins=[bins]).values}')
print(f'numpy histogram: {np.histogram(data, bins=bins)[0]}')
```
```
xhistogram: [0 0]
numpy histogram: [ 0 10]
```

Could we make it the case?

**Comment by dougiesquire** [comment]
Note, this comes about because of an inconsistency between `numpy.digitize` and `numpy.histogram`, see https://github.com/numpy/numpy/issues/4217

**Comment by rabernat** [comment]
Hi @dougiesquire, thanks a lot for this suggestion! I'm 👍  on being consistent with numpy.histogram, although it's frustrating the `digitize` and `histogram` have different behavior themselves!

Would you be willing to make a PR?

Sorry it took so long to reply to your issue. Very busy time of year for me!
