### ISSUE TITLE
Weighted hist example

### ISSUE THREAD

**Issue by dhruvbalwada** [xgcm/xhistogram#2]
It is not completely clear what the weighted histogram does. 

If I have data :
x = [0,0,1,1]
weights = [-2,-2, -3,-4] 

Is the weighted histogram 
the sum (xh = [ -4, -7]) or is it the mean (xh = [-2, -3.5])? 

I think it is the sum, but best to be clear.

**Comment by rabernat** [comment]
It is the sum. Under the hood it is just calling to numpy.histogram: https://docs.scipy.org/doc/numpy/reference/generated/numpy.histogram.html

That's where all the details are documented.
