### ISSUE TITLE
Support binning over datetime64 objects

### ISSUE THREAD

**Issue by WardBrian** [xgcm/xhistogram#25]
The method of adding a small increment to the bin (in [core.py](https://github.com/xgcm/xhistogram/blob/9992eba11eff9ee704e0f6755d521ab56cab9de3/xhistogram/core.py#L117)) leads to an error when trying to do time binning over a numpy datetime64-indexed coordinate, which are quite common in xarray. It would be really nice if this was supported.

**Comment by dougiesquire** [comment]
xhistogram uses the numpy/dask digitize functions, which do not currently support datetime objects. A workaround is to first view or cast your datetime data to a type that digitize can safely cast to floats, e.g.
```python
import pandas as pd
import numpy as np
from xhistogram.core import histogram

data = np.array(pd.date_range(start="2000-06-01", periods=60))
bins =  np.array(pd.date_range(start="2000-06-01", periods=3, freq='MS'))
data_i8 = data.view('i8')
bins_i8 = bins.view('i8')

histogram(data_i8, bins=bins_i8)
```

**Comment by dougiesquire** [comment]
Closing this issue, since binning over datetime objects is now supported (#44)
