### ISSUE TITLE
NaNs in histogram weights 

### ISSUE THREAD

**Issue by stb2145** [xgcm/xhistogram#26]
Was trying to plot sigma distribution time series and had trouble understanding how xhistogram was treating NaNs in the input data. Turns out there are NaNs in the input weights and it seems like when there's one NaNs value in a bin, `xhist` makes the entire bin Nan.

This is also noted in the [documentation tutorial](https://xhistogram.readthedocs.io/en/latest/tutorial.html?highlight=nans#Averaging-a-variable). A fix to this was to run `.fillna()` on the weights. I think clear documentation on this feature will be helpful.

**Comment by dougiesquire** [comment]
Thanks for reporting this @stb2145! Are you interested in submitting a PR to either improve the way NaNs are dealt with or to update the documentation?

**Comment by stb2145** [comment]
I just submitted PR #47. Please let me know if there are further changes I should make!

**Comment by dougiesquire** [comment]
Thanks @stb2145. Closed by https://github.com/xgcm/xhistogram/pull/47
