### ISSUE TITLE
Maintenance work and maintainers needed

### ISSUE THREAD

**Issue by rabernat** [xgcm/xhistogram#32]
We need to do some grunt work to keep this package maintainable

- [x] Migrate to github workflows (travis-ci.org will soon shut down)
- [x] Add automatic linting to CI (black, pep8)
- [x] Set up readthedocs integration for PRs
- [ ] Start adding mypy type hints

We **welcome any and all volunteers** who want to help with these unglamorous but important tasks.

More generally, "we" is actually still just me. There are no other maintainers of xhistogram. I would love to add more, especially since my response time can be very slow. Just say the word and I will grant you privs.

**Comment by dougiesquire** [comment]
I'm happy to help out where I can, but I'm new to some of these tools so I may be pretty slow to get going 🙂

**Comment by rabernat** [comment]
I have created @xgcm/xhistogram-dev and invited @dougiesquire to it. @raybellwaves and @TomNicholas would also fit here if interested.

**Comment by jrbourbeau** [comment]
Setting up readthedocs builds on PRs is relatively straightforward (we did this for Dask earlier this week based on @raybellwaves' suggestion 👍 ) but does require someone with admin access on readthedocs and (maybe) GitHub.

[Here](https://docs.readthedocs.io/en/stable/pull-requests.html) are the instructions for enabling things on readthedocs -- there's a box that needs to be checked in the readthedocs settings. 

Additionally, the readthedocs webhook in this repo may also need to be updated. There's a "Pull requests" box in the webhook that needs to be checked.

**Comment by rabernat** [comment]
Thanks to @jrbourbeau, we have checked off 3 of these items! I'm going to close this and open a new issue for type hints.
