### ISSUE TITLE
Support for density=True keyword

### ISSUE THREAD

**Issue by rabernat** [xgcm/xhistogram#4]
Numpy histogram has the `density` keyword, which normalized the outputs by the bin spacing.
https://docs.scipy.org/doc/numpy/reference/generated/numpy.histogram.html

We can easily support this in xhistogram, but it has to .be plugged in. Just opening this issue to make a note of it.

**Comment by bradyrx** [comment]
This still needs to be implemented, correct? I noticed that passing the keyword does nothing on the high-level function. It looks like it goes through to the private function which expects the keyword but does nothing with it. It would be good to have a `NotImplementedError` if one passes `True` to density. Or maybe the better PR would be to just implement it.

**Comment by bradyrx** [comment]
Okay, it looks fairly straight forward. I might open a PR on this shortly depending on how it goes...

**Comment by bradyrx** [comment]
I need to get familiar with the code base before trying to implement it. But my impression is that this has to be done somewhere in the private functions while we still retain knowledge of the original bins. The xarray object that is ultimately returned from `xhist` has centered coordinates for the bins.

To compute with `density=True` we need to diff the original bins (`db`) and then do `N / db / N.sum()`. However, in this case we should return `db` or the original bin edges as well to ensure the user can compute the integral appropriately.

Maybe the xhistogram object should always be returned with dimension `bins` and `bin_bounds`. Say a user computes a histogram with 11 bins over dimension x. The returned object would have dims `x_bin` of length 10 and `x_bin_bnds` of length 11.

**Comment by bradyrx** [comment]
**Another thought**: I think this gets more complicated by the fact that we expect geospatial data. The `numpy` function just applies `diff` to the bin boundaries understandably. Folks using `xhistogram` will commonly input bin boundaries of latitude and longitude in degrees. Diffing a 1x1 degree rectilinear grid gives `xhistogram` the impression that all the bin boundaries are equal. But this isn't the case on a globe where 1 degree of longitude varies by latitude.

**Comment by rabernat** [comment]
> Maybe the xhistogram object should always be returned with dimension `bins` and `bin_bounds`. Say a user computes a histogram with 11 bins over dimension x. The returned object would have dims `x_bin` of length 10 and `x_bin_bnds` of length 11.

That would be nice, except that then we can't return a DataArray, we have to return a Dataset. See this comment:

https://github.com/xgcm/xhistogram/blob/c53fea67ab8ed4cb47dac625301454433c9eab09/xhistogram/xarray.py#L146-L152

The only place that the centered bin coordinates are used is in the `xarray.py` module. All the real computations happen in `core.py`. This would be the place to apply the density logic. We could easily just copy numpy:

https://github.com/numpy/numpy/blob/117220ff29bcbc85bc888f8590d3653a9e9808f4/numpy/lib/histograms.py#L906-L908

**Comment by rabernat** [comment]
> **Another thought**: I think this gets more complicated by the fact that we expect geospatial data. The `numpy` function just applies `diff` to the bin boundaries understandably. Folks using `xhistogram` will commonly input bin boundaries of latitude and longitude in degrees. Diffing a 1x1 degree rectilinear grid gives `xhistogram` the impression that all the bin boundaries are equal. But this isn't the case on a globe where 1 degree of longitude varies by latitude.

The use cases we originally had in mind are for problems where the bin dimensions are truly orthogonal. Lat / lon binning is complicated because of spherical geometry. "Naive" calculation of bin sizes would work just fine with lat / lon bins. You could easily calculate a proper area metric for the grid cells outside of xhistogram.

**Comment by bradyrx** [comment]
Looks like https://github.com/xgcm/xhistogram/pull/17 just needs to be merged. @rabernat, I think this should be good to go.

**Comment by rabernat** [comment]
Thanks for the pings @dougiesquire and @bradyrx. I'm sorry I let this hang for so long. I lost track of lots of things during the past few months.

If either of you wants to review #17, that would be much appreciated. It's a subtle problem.
