### ISSUE TITLE
Error with multiple dask `args`

### ISSUE THREAD

**Issue by dougiesquire** [xgcm/xhistogram#48]
As of 0.1.3, xhistogram now fails when provided multiple dask `args`. This is because the dask version of `ravel_multi_index` that was [introduced into xhistogram in 0.1.3](https://github.com/xgcm/xhistogram/pull/31) does not actually replicate the API of the equivalent numpy function. Specifically, the numpy implementation can receive a tuple of integer arrays, whereas the [dask version cannot](https://github.com/dask/dask/issues/7580).

We actually don't have a test in our suite for multiple dask `args`, which is why this bug went uncaught until now.

I've opened an issue with dask, but we probably need to provide a more immediate fix for xhistogram. @rabernat, what do you think about reverting back to using [your wrapper of](https://github.com/xgcm/xhistogram/pull/31/files) `np.ravel_multi_index` until the issue is resolved with dask?

**Comment by dougiesquire** [comment]
Note, a fix is being implemented in dask here: https://github.com/dask/dask/pull/7584

**Comment by rabernat** [comment]
Now here https://github.com/dask/dask/pull/7594.

**Comment by dougiesquire** [comment]
Just to re-emphasise, xhistogram is currently broken for multiple dask `args` due to this issue. Depending on how long we anticipate dask/dask#7594 may take to be released, would it be worth reverting back to @rabernat's [wrapper](https://github.com/xgcm/xhistogram/pull/31/files#diff-46b9123aa3c280b48a21913005d1c54452bc87f45195036e97f0a6a7c443112fL42) of `np.ravel_multi_index` and releasing a temporary fix?

**Comment by rabernat** [comment]
> xhistogram is currently broken for multiple dask `args` due to this issue

Can't we fix this by pinning a compatible dask version here:

https://github.com/xgcm/xhistogram/blob/master/setup.py#L23

**Comment by dougiesquire** [comment]
> This code has been in for a long time:
> 
> https://github.com/xgcm/xhistogram/blob/master/xhistogram/duck_array_ops.py#L39

I'm not sure this is correct. I think this line was added in #31 just a few months ago. That PR switched from using a "dask-enabled" version of `ravel_multi_index` that you wrote, to using the official, but broken, dask version.

AFAICT we have two options:

1. revert back to using the approach we were using pre #31 until dask/dask#7594 is merged/release (i.e. add back in [this](https://github.com/xgcm/xhistogram/pull/31/files#diff-46b9123aa3c280b48a21913005d1c54452bc87f45195036e97f0a6a7c443112fL42) code)
2. wait for dask/dask#7594 to be merged/release.

**Comment by rabernat** [comment]
Yes @dougiesquire you're correct (and sorry for not following up sooner).

Which option do you think is best?

**Comment by jrbourbeau** [comment]
Quick update: https://github.com/dask/dask/pull/7594 was just merged and should be out in a `dask` release in ~1.5 weeks (not this Friday, but next Friday)

**Comment by jrbourbeau** [comment]
Just checking in, https://github.com/dask/dask/pull/7594 is now out in a dask release. Is it safe to close this issue? Perhaps we should bump `xhistogram`s minimum `dask` version

**Comment by dougiesquire** [comment]
> Just checking in, dask/dask#7594 is now out in a dask release. Is it safe to close this issue? Perhaps we should bump xhistograms minimum dask version

Thanks for the reminder @jrbourbeau. `xhistrogram` doesn't actually use `dask.array.ravel_multi_index` since the refactor to use `dask.array.blockwise` (#49), so there hopefully shouldn't be a need to pin a minimum dask version.
