### ISSUE TITLE
DOI for citation

### ISSUE THREAD

**Issue by roxyboy** [xgcm/xhistogram#55]
Could the developers add a Zenodo DOI so I can cite this package?
Thanks for the work you've put into this :)

**Comment by dougiesquire** [comment]
Thanks @roxyboy. Strangely I don't seem to be able to do this. xgcm repositories don't show up for me on Zenodo, despite Zenodo being listed as an authorised OAuth App for the organisation on my github account. Maybe @rabernat will have more luck?

**Comment by dougiesquire** [comment]
Closed by #73
