### ISSUE TITLE
Release v0.3?

### ISSUE THREAD

**Issue by rabernat** [xgcm/xhistogram#64]
We have done a fair bit of work on xhistogram recently. Once #44 is in, do we want to do a release?

**Comment by dougiesquire** [comment]
Maybe also include #65? Just a tiny addition.

**Comment by TomNicholas** [comment]
We should definitely merge the tests for dask chunking first (#57), but after that then @dougiesquire are you happy to do the release?

**Comment by dougiesquire** [comment]
> We should definitely merge the tests for dask chunking first (#57), but after that then @dougiesquire are you happy to do the release?

Sorry, missed this one somehow. Yup, happy to do a release 👍

**Comment by dougiesquire** [comment]
Closing since v0.3 is now released
