### ISSUE TITLE
Intermittent? test CI failures

### ISSUE THREAD

**Issue by jbusecke** [xgcm/xhistogram#74]
I mentioned this over in #73, but it might be worth raising a separate issue here. It seems that there is a flaky test in the CI suite. 

See these three runs: 
<img width="845" alt="image" src="https://user-images.githubusercontent.com/14314623/144919621-75de9862-df8d-42b0-abb8-cca2cd2ae1c5.png">
They should all contain the exact same code, but some of them pass and [one fails](https://github.com/xgcm/xhistogram/actions/runs/1537432658).

I just restarted the same tests twice in #73 and the issue went away. It seems that this is only happening in the `Tests / test (macos-latest, 3.7) (pull_request) `run.

cc @TomNicholas

**Comment by dougiesquire** [comment]
I *think* this issue has been fixed (or at lease stopgapped) by #82. Please reopen if not.
